services:
  - type: web
    name: e-learning-backend
    env: python
    buildCommand: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      source $HOME/.cargo/env
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: e-learning-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: BACKEND_CORS_ORIGINS
        value: https://your-frontend-url.com
      - key: CARGO_HOME
        value: /opt/render/project/src/.cargo
      - key: RUSTUP_HOME
        value: /opt/render/project/src/.rustup
